# Generated by Django 4.2.18 on 2025-01-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/assets/img/blog/default.jpg', upload_to='blog/'),
        ),
    ]
